name: Build and Release

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Bundle resources
        run: |
          # 确保目录存在
          mkdir -p bundled
          
          # 使用 -name 参数导出变量
          fyne bundle -o bundled/resources.go -pkg bundled -name Logo assets/Logo.png

          
          # 验证生成的文件
          if [ ! -f "bundled/resources.go" ]; then
            echo "❌ Resource bundle failed to generate"
            exit 1
          fi

      - name: Build application
        run: |
          go build -o PomodoroTimer.exe .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PomodoroTimer-Windows
          path: PomodoroTimer.exe