name: Build and Release Pomodoro Timer

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: ['1.22']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        run: |
          go install github.com/akavel/rsrc@latest
          go install github.com/fyne-io/fyne-cross@latest

      - name: Prepare resources
        run: |
          # 创建 manifest 文件
          New-Item -Path xtimer.manifest -ItemType File -Value @"
          <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
          <assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
            <assemblyIdentity 
              version="1.0.0.0"
              processorArchitecture="amd64"
              name="XTimer"
              type="win32"
            />
            <description>Pomodoro Timer Application</description>
            <dependency>
              <dependentAssembly>
                <assemblyIdentity
                  type="win32"
                  name="Microsoft.Windows.Common-Controls"
                  version="6.0.0.0"
                  processorArchitecture="amd64"
                  publicKeyToken="6595b64144ccf1df"
                  language="*"
                />
              </dependentAssembly>
            </dependency>
            <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
              <security>
                <requestedPrivileges>
                  <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
                </requestedPrivileges>
              </security>
            </trustInfo>
          </assembly>
          "@
          
          # 转换 PNG 为 ICO (需要安装 ImageMagick)
          choco install imagemagick -y
          magick convert assets/logo.png -define icon:auto-resize=256,128,64,48,32,16 assets/logo.ico

      - name: Generate resource file
        run: |
          # 确保使用绝对路径
          $icoPath = Resolve-Path -Path "assets/logo.ico"
          rsrc -manifest xtimer.manifest -ico "$icoPath" -o rsrc.syso

      - name: Build Windows executable
        run: |
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          $env:CGO_ENABLED = "1"
          # 添加 -tags=windows 确保嵌入资源
          go build -tags=windows -ldflags="-s -w -H=windowsgui" -o XTimer.exe main.go

      - name: Compress executable
        run: |
          choco install upx -y
          upx --best XTimer.exe
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: XTimer-Windows
          path: XTimer.exe

  release:
    needs: [build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/XTimer-Windows/XTimer.exe
          tag_name: v1.0.0
          name: Release v1.0.0
          body: |
            Pomodoro Timer Application
            - Windows: XTimer.exe
          draft: false
          prerelease: false