name: Build and Release Pomodoro Timer

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest  # 使用 Linux 环境，因为 fyne-cross 需要 Docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install fyne-cross
        run: |
          # 安装 fyne-cross
          go install github.com/fyne-io/fyne-cross@latest
          
          # 验证安装
          fyne-cross version

      - name: Build with fyne-cross
        run: |
          
          # 构建 Windows 应用
          echo "构建 Windows 应用"
          fyne-cross windows -arch amd64 -icon assets/Logo.ico -output XTimer.exe
          
          # 验证构建结果
          if [ ! -f "fyne-cross/bin/windows-amd64/XTimer.exe" ]; then
            echo "❌ 构建失败：未找到可执行文件"
            exit 1
          fi
          
          echo "✅ 构建成功"

      - name: Compress executable (optional)
        run: |
          # 安装 UPX
          sudo apt-get update
          sudo apt-get install -y upx
          
          # 压缩可执行文件
          upx --best --lzma fyne-cross/bin/windows-amd64/XTimer.exe

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: XTimer-Windows
          path: fyne-cross/bin/windows-amd64/XTimer.exe

  release:
    needs: [build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: XTimer-Windows
          path: release

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: release/XTimer.exe
          tag_name: v1.0.0
          name: Release v1.0.0
          body: |
            Pomodoro Timer Application
            
            Features:
            - Built with fyne-cross
            - Windows executable
          draft: false
          prerelease: false